### ISSUE TITLE
New line in Timeline 

### ISSUE THREAD

**Issue by niall-mcgowan** [YoussefRaafatNasry/portfolYOU#23]
Hi, trying to figure out how to create new lines within the timeline.yml file. 

Trying to bullet point experience in each of the roles in the description field.

Currently, no matter what I do, it comes back as a simple string, cutting out the line breaks at the end of each sentence.

I've been trying to fix for the last day. 😂 Any help is greatly appreciated.

**Comment by YoussefRaafatNasry** [comment]
Can you show me how the output looks like and your `timeline.yml`'s content?

**Comment by niall-mcgowan** [comment]
![2020-02-24 12_58_20-Window](https://user-images.githubusercontent.com/44233626/75154379-7fdf1200-5705-11ea-9d19-965a5881d202.png)
![2020-02-24 12_59_10-Window](https://user-images.githubusercontent.com/44233626/75154380-7fdf1200-5705-11ea-8b43-10a25d2e5001.png)

I've tried the pipe symbol, as I've read online this should fix the issue. I've tried so many iterations its not possible to list them all.

Thank you for getting back to me so quickly, I really appreciate it 👍

**Comment by YoussefRaafatNasry** [comment]
Since this text is converted into HTML, you can use HTML line breaks as follows:

```yaml
- title: Software Engineer, Google, UK
  from: 2018
  to: present
  description: • Lorem ipsum dolor sit amet, <br />
               • consectetur adipiscing elit, <br />
               • sed do eiusmod tempor incididunt <br />
               • ut labore et dolore magna aliqua' <br />
```
