### ISSUE TITLE
Speakerdeck icon doesn't work

### ISSUE THREAD

**Issue by luchiago** [YoussefRaafatNasry/portfolYOU#31]
When I try to use speakerdeck icon, putting on social-media.yml, doesn't work

```yaml
_data/social-media.yml

speakerdeck:
  url   : https://speakerdeck.com/
  icon  : fab fa-speaker-deck
  color : 009287

_config.yml
speakerdeck       : luchiago
```
