### ISSUE TITLE
Google Analytics Integration Support

### ISSUE THREAD

**Issue by bhattumang7** [YoussefRaafatNasry/portfolYOU#44]
I need to include the Google anaytics tag in header. I don't seee a way to do that. Please help.

**Comment by rribeiro1** [comment]
@bhattumang7 I have opened this PR https://github.com/YoussefRaafatNasry/portfolYOU/pull/43 to add Google Analytics support, after merging you can use by adding this in your `_config.yml`:

```yml
### Analytics ###
analytics:
  enabled: false  # Set true to enable analytics
  google:
    tracking_id: UA-XXXXXXX-1
```
