### ISSUE TITLE
How to add new category?

### ISSUE THREAD

**Issue by Dishant-P** [YoussefRaafatNasry/portfolYOU#49]
I have little to no idea about this, so sorry if the issue is too naive. But I wanted to know how can I add same page like Blog, and rename it and add other content there. So same theme like the blogs page but different content. 
Thanks.

**Comment by lillemets** [comment]
There's actually a better implementation of this, one that is used by some Jekyll templates. Each category or tag could be presented as a separate menu item. So all the posts that have a tag *something* are shown if you open *something* from the menu. I'd love to see this implemented here, too.

**Comment by YoussefRaafatNasry** [comment]
First of all, sorry for the late response.

To add a new category like posts or projects, you need to do the following — _I would assume that the new category is called **articles**_: 

1. Add the new category to `_config.yaml`:

    ```yaml
    collections:
      # ....
      articles:
        output: true
        permalink: /articles/:name
    
    # ....
    
    defaults:
      # ....
      - scope:
          path: ""
          type: "articles"
        values:
          layout: "page"
    ```

1. Create a folder called `_articles` and add your markdown files there. _You must follow the same [front matter](https://jekyllrb.com/docs/front-matter/) as [posts](https://youssefraafatnasry.github.io/portfolYOU/docs/#posts).

1. Create a page called `articles.html` in `pages` directory and add the following content to it:

    ```html
    ---
    layout: default
    title: Articles
    weight: 5
    permalink: /articles/
    ---
    
    <div class="card-group mt-2">
    
    
        {% for post in site.articles %}
            <!-- Note that this must be called "post" because the post-card wasn't
                 made to be reused, we might improve this in the future to allow this. -->
            {% include blog/post-card.html %}
        {% endfor %}
    
    </div>
    ```
