### ISSUE TITLE
More Social Icons

### ISSUE THREAD

**Issue by renyuneyun** [YoussefRaafatNasry/portfolYOU#5]
The document says
> use any of those libraries’ components anywhere in the project

But if I write `gitlab : XXX` under the `author` section of the config, nothing appears. It seems this setting is just ignored when processing, because there is no HTML element related to it.

So, how to use other icons (of fontawesome) for contact information?

(I'm not a front-end developer so if this question is dumb... please can you point me to some relevant documents?)

**Comment by YoussefRaafatNasry** [comment]
Will add more social icons support soon, please mention if you need more icons, _not just gitlab.

**Comment by renyuneyun** [comment]
Thanks :)

Is it possible to make this to be general enough to allow any fontawesome icons (by just passing the fontawesome icon name as the key)?

I haven't thought about that fully, but for me, I would be interested in gitlab, mastodon, hubzilla (or activitypub) icons mostly; matrix.org is also likely (but I'm not quite sure yet).

**Comment by YoussefRaafatNasry** [comment]
You can add any custom social media service now as follows:

1.  `_data/social-media.yml`: 

    ```yml
    service_name:
      url   : https://....
      icon  : get it from https://fontawesome.com/icons
      color : get it from https://brandcolors.net/
    ```

2. `_config.yml`:

    ```yml
    author:
      service_name : your_username
    ```
