### ISSUE TITLE
How to/Can I change the URL of a project

### ISSUE THREAD

**Issue by keunes** [YoussefRaafatNasry/portfolYOU#79]
Hello,

Exploring this theme further, I thought to change the URL of the project pages I created under `_projects`. Reason is that I would like to sort my projects (using the `(x)` indication as in the example files), while not having the number in the actual url (e.g. remove the number from `www.site.com/projects/4-example-project`).

I tried adding a `permalink` Front Matter, but that doesn't seem to work (or I'm doing something wrong). Could support for changing the URLS be added? Or if it's possible, how should I do it?

**Comment by keunes** [comment]
Actually, I see this code in `_config.yml`:
```
### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
```

How come `name` is not picked up in the URL - does it not refer to the same field in the Front Matter?
